# Generated by Django 6.0.1 on 2026-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='urged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='催单时间'),
        ),
    ]
