# Generated by Django 6.0.1 on 2026-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_urged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='today_modified_count',
            field=models.IntegerField(default=0, verbose_name='今日修改次数'),
        ),
    ]
