# Generated by Django 6.0.1 on 2026-01-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_deleted_at_appointment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_before_deletion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除前最后登录时间'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='to_be_deleted',
            field=models.BooleanField(default=False, verbose_name='标记为待删除'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='to_be_deleted_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='待删除通知时间'),
        ),
    ]
