# Generated by Django 6.0.1 on 2026-01-19 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_last_login_before_deletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProcessingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_removed', models.BooleanField(default=False, verbose_name='已移除')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment', verbose_name='预约')),
            ],
            options={
                'verbose_name': '处理池记录',
                'verbose_name_plural': '处理池记录',
            },
        ),
    ]
