# Generated by Django 6.0.1 on 2026-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctorprocessingpool'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_processed_priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '危')], default=1, help_text='记录医师上次处理的1-3级预约的优先级，用于轮询算法', verbose_name='上次处理的优先级'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '危')], default=4, verbose_name='优先级'),
        ),
    ]
