# Generated by Django 6.0.1 on 2026-01-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_last_processed_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '危')], default=1, verbose_name='优先级'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('wechat_id', models.CharField(max_length=30, verbose_name='微信号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('overview', models.TextField(blank=True, verbose_name='概述（仅医师可见）')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('completed', '已完成')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='归属账号')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_profiles', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='记录内容')),
                ('record_type', models.CharField(choices=[('doctor', '医师填写'), ('user', '用户填写')], max_length=20, verbose_name='记录类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.profile', verbose_name='档案')),
            ],
            options={
                'verbose_name': '档案记录',
                'verbose_name_plural': '档案记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
