# Generated by Django 6.0.1 on 2026-01-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appointment_priority_profile_profilerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
