# Generated by Django 6.0.1 on 2026-01-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerecord',
            name='record_type',
            field=models.CharField(choices=[('user', '访客'), ('doctor_public', '医师（公开）'), ('doctor_private', '医师（仅医师）')], max_length=20, verbose_name='记录类型'),
        ),
    ]
