# Generated by Django 6.0.1 on 2026-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profilerecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_urged',
            field=models.BooleanField(default=False, verbose_name='是否催促'),
        ),
    ]
