# Generated by Django 6.0.1 on 2026-01-27 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_announcement_view_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='上次查看公告时间'),
        ),
    ]
